name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        What is the problem?
        What did you expect?
        You paste or drop screenshots here 
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: Project file & How to reproduce
      description: "*Please* upload a ZIP archive containing the project file used when the problem arise. Please export it just before the problem occur. Even if you did nothing and/or there is no object, export it! (it contains your current configuration)."
      placeholder: |
        `File`->`Export project as...` then zip it & drop it here
        Also, if needed include the steps to reproduce the bug:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? You can have the full version in `Help` -> `About superslicer`.
      placeholder: 2.4.60.2
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      description: with the version if possible
      placeholder: windows 10 / ubuntu 22.04 / macos 15
    validations:
      required: false
  - type: input
    id: printer
    attributes:
      label: Printer model
      description: May be useful to update default profile, or understand why to creates a problem
      placeholder: voron 2.4 with afterburner
    validations:
      required: false
