name: C/C++ deps for macos

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir in deps
      run: mkdir deps/build
    - name: cmake deps
      working-directory: ./deps/build
      run: cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13"
    - name: make deps
      working-directory: ./deps/build
      run: make
    - name: zip the result
      working-directory: ./deps/build
      run: zip -r deps_mac.zip destdir
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./deps/build/deps_mac.zip
        asset_name: deps_mac.zip
        asset_content_type: application/zip
